# Generated by Django 5.2.8 on 2025-11-06 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária semanal')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal', max_length=7)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone FontAwesome', max_length=50)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(choices=[('6ano', '6º Ano'), ('7ano', '7º Ano'), ('8ano', '8º Ano'), ('9ano', '9º Ano'), ('1em', '1º Ano EM'), ('2em', '2º Ano EM'), ('3em', '3º Ano EM')], max_length=10)),
                ('ano_letivo', models.IntegerField(default=2025)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=20)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'perfil__tipo': 'aluno'}, related_name='turmas_aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['serie', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil__tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_lecionadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='escola.turma')),
            ],
            options={
                'verbose_name': 'Disciplina da Turma',
                'verbose_name_plural': 'Disciplinas das Turmas',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
